; Moodle performance configuration
; Generated by moodle-deployer

memory_limit = 512M
upload_max_filesize = 200M
post_max_size = 200M
max_execution_time = 300
max_input_vars = 5000

; OPcache settings
opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 60
opcache.fast_shutdown = 1
